In [1]:
import pandas as pd

In [2]:
# reads csv file
df = pd.read_csv('players_20.csv')
# set index
df.set_index('short_name', inplace=True)
# select column
df = df[['long_name', 'age', 'dob', 'height_cm', 'weight_kg', 'nationality', 'club']]

In [3]:
# show dataframe
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

# query()

In [4]:
# select players older than 34
df.query("age>34")

# exercise: write the equivalent boolean slicing
# df[df['age']>34]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Z. Ibrahimović,Zlatan Ibrahimović,37,1981-10-03,195,95,Sweden,LA Galaxy
Pepe,Képler Laveran Lima Ferreira,36,1983-02-26,188,81,Portugal,FC Porto
G. Buffon,Gianluigi Buffon,41,1978-01-28,192,92,Italy,Juventus
Casillas,Iker Casillas Fernández,38,1981-05-20,185,84,Spain,FC Porto
F. Quagliarella,Fabio Quagliarella,36,1983-01-31,180,79,Italy,Sampdoria
...,...,...,...,...,...,...,...
N. Hunt,Nicky Hunt,35,1983-09-03,185,86,England,Crewe Alexandra
K. Ogi,荻 晃太,36,1983-05-05,185,76,Japan,Vissel Kobe
J. McCombe,Jamie McCombe,36,1983-01-01,196,79,England,Lincoln City
G. Maley,Gary Maley,36,1982-08-03,188,90,Scotland,Livingston FC
Zhou Ting,周挺,40,1979-02-05,182,73,China PR,Dalian YiFang FC

In [5]:
# select players older than 34 from Italy
df.query("age>34 and nationality=='Italy'")

# exercise: write the equivalent boolean slicing
# df[(df['age']>34) & (df['nationality']=='Italy')]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
G. Buffon,Gianluigi Buffon,41,1978-01-28,192,92,Italy,Juventus
F. Quagliarella,Fabio Quagliarella,36,1983-01-31,180,79,Italy,Sampdoria
D. De Rossi,Daniele De Rossi,35,1983-07-24,184,83,Italy,Boca Juniors
A. Mirante,Antonio Mirante,35,1983-07-08,193,79,Italy,Roma
A. Diamanti,Alessandro Diamanti,36,1983-05-02,180,75,Italy,Western United FC
C. Maggio,Christian Maggio,37,1982-02-11,184,79,Italy,Benevento
D. Dainelli,Dario Dainelli,40,1979-06-09,191,78,Italy,Livorno
F. Marchetti,Federico Marchetti,36,1983-02-07,188,83,Italy,Genoa
F. Peluso,Federico Peluso,35,1984-01-20,188,82,Italy,Sassuolo
C. Terzi,Claudio Terzi,35,1984-06-19,180,69,Italy,Spezia
A. Rosina,Alessandro Rosina,35,1984-01-31,170,69,Italy,US Salernitana 1919
D. Maietta,Domenico Maietta,36,1982-08-03,184,75,Italy,Empoli
A. Cordaz,Alex Cordaz,36,1983-01-01,188,83,Italy,Crotone
S. Floccari,Sergio Floccari,37,1981-11-12,180,79,Italy,SPAL
M. Iori,Manuel Iori,37,1982-03-12,182,72,Italy,Cittadella
M. Stefani,Mirco Stefani,35,1984-01-25,180,80,Italy,Pordenone
G. Pegolo,Gianluca Pegolo,38,1981-03-25,183,76,Italy,Sassuolo
D. Gastaldello,Daniele Gastaldello,36,1983-06-25,185,77,Italy,Brescia
D. Moscardelli,Davide Moscardelli,39,1980-02-03,185,80,Italy,Pisa
E. Calaiò,Emanuele Calaiò,37,1982-01-08,179,75,Italy,US Salernitana 1919
D. Croce,Daniele Croce,36,1982-09-09,173,70,Italy,US Cremonese
A. Rosati,Antonio Rosati,36,1983-06-26,195,88,Italy,Torino
F. Mazzeo,Fabio Mazzeo,35,1983-07-24,177,77,Italy,Livorno
M. De Agostini,Michele De Agostini,35,1983-11-27,180,78,Italy,Pordenone
A. Pomini,Alberto Pomini,38,1981-03-17,185,80,Italy,Venezia FC
F. Evacuo,Felice Evacuo,36,1982-08-23,187,88,Italy,Trapani
G. Munari,Gianni Munari,36,1983-06-24,190,84,Italy,Parma
L. Pagliarulo,Luca Pagliarulo,35,1984-02-29,187,80,Italy,Trapani
C. Del Grosso,Cristiano Del Grosso,36,1983-03-24,171,66,Italy,Pescara
R. Vitiello,Roberto Vitiello,36,1983-05-08,176,72,Italy,Castellammare di Stabia
A. Bruno,Alessandro Bruno,35,1983-07-04,180,70,Italy,Pescara
T. Berni,Tommaso Berni,36,1983-03-06,185,80,Italy,Inter
P. Gori,Pier Graziano Gori,39,1980-05-10,189,83,Italy,Benevento
S. Farelli,Simone Farelli,36,1983-02-19,186,82,Italy,Pescara

In [6]:
# add a not operator to the first example
df.query("not(age>34)")

# exercise: write the equivalent boolean slicing
# df[~(df['age']>34)]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [7]:
# convert height to meters and select those with height above 1.8
df.query("height_cm/100 > 1.8")

# exercise: write the equivalent boolean slicing
# df[df['height_cm']/100>1.8]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
M. ter Stegen,Marc-André ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona
V. van Dijk,Virgil van Dijk,27,1991-07-08,193,92,Netherlands,Liverpool
...,...,...,...,...,...,...,...
P. Martin,Paul Martin,20,1999-01-05,188,84,Republic of Ireland,Waterford FC
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [8]:
# select players that were born after 1990

# check out data types
df.dtypes
# conver "dob" column to datetime type
df['dob'] = df['dob'].astype('datetime64')
# query
df.query("dob.dt.year > 1990")

# exercise: write the equivalent boolean slicing
df[df['dob'].dt.year>1990]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
M. ter Stegen,Marc-André ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC